language: go
go:
  - 1.14
  - 1.15

addons:
  apt:
    packages:
      - libpam0g-dev

sudo: False
dist: bionic

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./store -covermode=count -coverprofile=./store/.coverprofile
  - go test -v ./sasl -covermode=count -coverprofile=./sasl/.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
  - make
  - make -C pam

branches:
  only:
    - master
