language: go
go:
  - 1.5
  - 1.6
  - 1.7

addons:
  apt:
    packages:
      - libpam0g-dev

sudo: False
dist: trusty

install:
  - go get -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./store -covermode=count -coverprofile=coverage-store.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage-store.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -v ./sasl -covermode=count -coverprofile=coverage-sasl.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage-sasl.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - make -C app
  - make -C pam

branches:
  only:
    - master

env:
  global:
    secure: oSqS/i3U8ShxYIMbpJXf5867HK7rft2HxmYhTYrrgBLsWtJeeSkN/BP3u5d3qjtVp238ZX7U04VskwIQ7q8VMz8ZJrv8/xLww7CMJ4eKl2HFq5vAY9FVO9xckzT+YdYQ2gwDdG/eamCTPjVHxJj0LSBPuoGQkkvYlLTedlEW/E0SMezmX0DOZXd+HHsJOLePTbZKMxCRHcAHtrDu6Aj4E3INxgC67QuxCaixj6JoJcc+pGOWxTkiNBloUk+B3bSxMcXZG39dvXhsprB040hm/yxL9KkBdWgZ6QnPaK1ix4nCLGhkIrJRHYyp4wkm3bcEjlVK2rgsTatrgyCdangH4zXw6cPaxUaHEQ4g/wwaBWOsOO59doyeUGGVrOjQCbCo4fbGyS0NcL23f+NHQLmESodbMnly/Fm1y5j+3saz7/3Iw0BDA5ZFQ6J4GrZziTF8mbY3lwDYqGfi6Q7Xh36qrQvKDnl/dOnUBsPGtkKarNmv9cBhNOYk8XixUohSBHYwBPV0qoGh1AVKHzUZDAwzMrTOSmcSOu+6jaDE0hHDG5AtZODDHqV+NH+cnRQ9QmB1YpPnzBuNRR0vy98zIEtZfbV+edHT5yesH8QdVmRakEX6xn5ECN0HVSHcfDMlFj0knJ1nZ8Rzo1J+mzrXDlxS2chkmPaAXr4DQluoWtJ2RHQ=
