language: go
go:
  - 1.5
  - 1.6
  - 1.7

addons:
  apt:
    packages:
      - libpam0g-dev

sudo: required
dist: trusty

install:
  - go get -v -t ./...
script:
  - go test -v ./store
  - go test -v ./sasl
  - make -C app
  - make -C pam

branches:
  only:
    - master
