language: go
go:
  - 1.5
  - 1.6
  - 1.7

addons:
  apt:
    packages:
      - libpam0g-dev

sudo: False
dist: trusty

install:
  - go get -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./store -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - go test -v ./sasl -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - make -C app
  - make -C pam

branches:
  only:
    - master
