on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64, arm64]
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "./cmd/whawty-auth"
        binary_name: "whawty-auth"
        pre_command: export CGO_ENABLED=0
        extra_files: AUTHORS LICENSE LICENSE.zxcvbn README.md doc/man/whawty-auth.8
        md5sum: false
        sha256sum: true
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: app
        image-platform: linux/arm64,linux/amd64,linux/i386
        extract-git-tag: true
    - uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: sync
        image-platform: linux/arm64,linux/amd64,linux/i386
        extract-git-tag: true
        build-context: ./contrib/sync
        custom-args: --build-arg=GOKR_RSYNC_VERSION="0.1.0"
